Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 2560.6762000000003ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
3/10/2020 2:16:33 PM System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 22
Request finished in 2718.3177ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 131.6396ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
3/10/2020 2:17:58 PM The Error is occured : System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 22
Request finished in 245.80780000000001ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 129.9693ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
3/10/2020 2:19:37 PM The Error is occured : System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 22
Request finished in 246.43550000000002ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 2293.6716ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
3/10/2020 2:19:58 PM The Error is occured : System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 22
Request finished in 2427.5533ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 1352.44ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
3/10/2020 2:20:42 PM The Error is occured : System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 22
Request finished in 6151.7415ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 1186.4831000000001ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
3/10/2020 2:21:22 PM The Error is occured : System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 22
Request finished in 4690.1185000000005ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 1227.8457ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Request finished in 3962.2279000000003ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 2650.5986000000003ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Request finished in 15273.077500000001ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 1196.7236ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Request finished in 4051.6461000000004ms 200 
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 1010.5942ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 23
An unhandled exception has occurred while executing the request.
Request finished in 8184.640200000001ms 500 text/html; charset=utf-8
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite
Request starting HTTP/2.0 GET https://localhost:44368/  
Executing endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executed action NorthwindSite.Controllers.HomeController.Index (NorthwindSite) in 1006.9292ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Index (NorthwindSite)'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NorthwindSite.Controllers.HomeController.Index() in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Controllers\HomeController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NorthwindSite.Extensions.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger) in C:\projects\dot-net-mentoring-a1\module_7\NorthwindSite\NorthwindSite\Extensions\ErrorLoggingMiddleware.cs:line 23
An unhandled exception has occurred while executing the request.
Executing endpoint 'NorthwindSite.Controllers.HomeController.Error (NorthwindSite)'
Route matched with {action = "Error", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Error() on controller NorthwindSite.Controllers.HomeController (NorthwindSite).
Executing ViewResult, running view ErrorFriendly.
Executed ViewResult - view ErrorFriendly executed in 96.1992ms.
Executed action NorthwindSite.Controllers.HomeController.Error (NorthwindSite) in 874.7234000000001ms
Executed endpoint 'NorthwindSite.Controllers.HomeController.Error (NorthwindSite)'
Request finished in 6359.893ms 500 text/html; charset=utf-8
